### ISSUE TITLE
max transaction limit check in tx/send 

### ISSUE THREAD

**Issue by paolocappelletti** [ZencashOfficial/bitcore-node-zen#5]
The maximum transaction limit in the explorer /tx/send endpoint appears to be lower than the  expected (100kbytes).
For example an attempt to send the following transaction:
inputs lenght: 496 
outputs lenght: 2
which had a serialized hex string of  73298 bytes 
returned  an endpoint error: "request entity too large".

From some test made, the actual accepted limit appears to be 50k
For example this one was successfull:
https://explorer-testnet.horizen.global/tx/07107fc1f266257dc013f4f7725485f99ee0d0c0ae2e3faf8869c1911df302fb
Maybe is checked the  string length instead of its bytelength?

**Comment by vietvu-nguyen** [comment]
I was facing this problem before. I had to break utxos into smaller chunks based on an average number of utxos that went through, and send one by one.

**Comment by cronicc** [comment]
This has been solved by adding
```
"servicesConfig":{
  "web":{
    "jsonRequestLimit":"210kb"
  }, ...
}
```
to bitcore-node.json config.
